### PR TITLE
Enable EBS encryption by default

### PR DESCRIPTION
**Pull request by huynguyent**
* Enable EBS encryption by default
* Allow encryption EBS volume with custom KMS key
* Added two tests for the new feature. However they are failing because of an issue with moto library. These tests will pass as soon as version 3.1.15 is released. I make these as skipped for now but I've verify the behavior manually. More info on the issue: https://github.com/spulec/moto/issues/3219

### CODE REVIEW

**Comment by tekumara** [comment]
Nice one 🎉 

FYI you can also [enable default ebs encryption at the account level](https://docs.aws.amazon.com/cli/latest/reference/ec2/enable-ebs-encryption-by-default.html) so it's automatically applied to all volume creation

**Comment by huynguyent** [comment]
@tekumara Thanks 😄 
I also saw the default encryption option while looking into this, but I decided to apply encryption for each instance since a launch command should only affect the instance it's creating. Maybe we should have another aec command to enable default encryption account-wide?

**Comment by tekumara** [comment]
Yeh that's right, it has an account-wide impact which means all future volumes are automatically encrypted and any IAM roles accessing EBS need to also have access to the key.

aec probably can't add much value over the existing `aws ec2` commands here, which for a CMK are:
```
aws ec2 enable-ebs-encryption-by-default
aws ec2 modify-ebs-default-kms-key-id  --kms-key-id $KEY_ID
```

**Comment by tekumara** [comment]
BTW, I notice you've changed the default encrypted, which is a different default from the EC2 API, so possibly surprising to newcomers. I wonder if the default should be unencrypted, but if a kms-key-id is specified in *ec2.toml* then encryption is enabled.

**Pull request merged**
