### PR TITLE
feat: ssm describe with name filters

### PR DESCRIPTION
**Pull request by tekumara**
eg: List running instances containing `gaga` in the name:

```
aec ssm describe -q gaga
```

### CODE REVIEW

**Review by mhasanbulli — COMMENTED** [review]
This is pretty neat. It runs into a small issue though. If you are matching for a string that repeats a lot in the `Name` attribute, you get a client error from `botocore`. For example, in my case, issuing `aec ssm describe -q compute` gives

```python
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DescribeInstanceInformation operation: The number of tag values for tag:Name was 35. Max: 5.
```

**Comment by tekumara** [comment]
Ah well spotted... since that's a limitation of the API, when there are than 5 names we'll have to filter them out in the API.

**Comment by tekumara** [comment]
Ah well spotted... since that's a limitation of the API, when there are than 5 names we'll have to filter them out client-side.

**Comment by tekumara** [comment]
I'm tempted to merge this now and address the limitation in a future PR.

**Review by mhasanbulli — APPROVED** [review]
🚀

**Pull request merged**
